name: Deploy to Server

on:
  push:
    branches:
      - main # or any branch you want to trigger the sync from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Sync repo to server
        run: |
          ssh -o StrictHostKeyChecking=no root@68.183.142.6 << 'EOF'
            cd ~/TagMyStickies
            git pull origin main
            chmod +x linuxProdStartupScript.sh
            ./linuxProdStartupScript.sh
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }} # Set this up in GitHub Secrets
